### ISSUE TITLE
Timestamp Serialization Format

### ISSUE THREAD

**Issue by scisci** [opentimestamps/python-opentimestamps#1]
Based on the ots command line program, the Stamp command returns a timestamp formatted like this:

    {
        'txid':b2lx(txid),
        'nonce':b2x(nonce),
        'addr':str(addr)
    }

The Complete command takes that timestamp and if the block is complete, returns a timestamp that looks like this

    [
        [merkle_path...],
        [timestamp header]
    ]

The disparity between the two formats should be reconciled. If we want to create a function to read a timestamp, it doesn't seem good to first check if it is an array or an object, etc. Maybe the timestamp returned by the Stamp command can match the array-style and just put the txid, addr, in the header area.

**Comment by petertodd** [comment]
Closing - everything's been rewritten so the question isn't relevant anymore. :)
