### ISSUE TITLE
You service is sh*t for Bitcoin community :-E

### ISSUE THREAD

**Issue by Perlover** [opentimestamps/python-opentimestamps#17]
Hi,

You service is sh*t for Bitcoin community :-E
You use UTXO for proof and a database of UTXO permanently grows from your proof transactions!
You could use OP_RETURN as it do https://proofofexistence.com/

It's right way!

**Comment by petertodd** [comment]
See https://github.com/opentimestamps/java-opentimestamps/issues/6#issuecomment-309668391
