### ISSUE TITLE
Complete release of version 0.2.1

### ISSUE THREAD

**Issue by erikarvstedt** [opentimestamps/python-opentimestamps#26]
Version `0.2.1` contains an import segwit fix and is already released on [pypi](https://pypi.python.org/pypi/opentimestamps). 
Completing the release by updating `__version__` and adding a Git tag would be a great help for packaging the library. (In my case: I'd like to add it to [nixpkgs](https://github.com/NixOS/nixpkgs), along with the client and server.)

**Comment by erikarvstedt** [comment]
Sorry, I've just noticed that the release is marked as beta on pypi.
I thought the Git repo was lagging behind an official release.
Case closed.

**Comment by petertodd** [comment]
Sorry, I think that was my mistake! Not sure what happened there; I may have just forgotten to do a git push.

It's now fixed: https://github.com/opentimestamps/python-opentimestamps/tree/python-opentimestamps-v0.2.1
