### ISSUE TITLE
Failed to create timestamp: need at least 2 attestations but received 0 within `timeout`

### ISSUE THREAD

**Issue by hatgit** [opentimestamps/python-opentimestamps#37]
I am getting this error and wondering if the service is still available or if this error is related to a problem locally on my end: 

`Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com
Submitting to remote calendar https://ots.btc.catallaxy.com
Failed to create timestamp: need at least 2 attestations but received 0 within `timeout`

**Comment by petertodd** [comment]
Curious!

The calendars are definitely up and working, so chances are there was something wrong on your end. Is the problem still happening? What does the verbose `-vv` output produce?

**Comment by hatgit** [comment]
Hi Peter, 
This command also doesn't seem to be running the tests? (is that the right way to add the verbose command for additional info?) Thanks!

`python3` -m unittest discover -v`

----------------------------------------------------------------------
`Ran 0 tests in 0.000s`

**Comment by petertodd** [comment]
Oh, I mean:

    ots -vv stamp filename.txt

Using the full path should definitely work; if it doesn't maybe there's something else wrong with your setup?

**Comment by hatgit** [comment]
Seems like I am getting some ssl error after running with `ots` -vv stamp`:

`Doing` 2-of-4 request, timeout is 5 seconds
Submitting to remote calendar https://a.pool.opentimestamps.org
Submitting to remote calendar https://b.pool.opentimestamps.org
Submitting to remote calendar https://a.pool.eternitywall.com
Submitting to remote calendar https://ots.btc.catallaxy.com
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
Failed to create timestamp: need at least 2 attestations but received 0 within timeout`

Thanks for the help with this, would love to get it to work.

**Comment by petertodd** [comment]
Ah! That explains it.

What exactly is your platform? That means while you could connect to the servers, your local python setup doesn't have the necessary root certs to verify the HTTPS connection.

We should figure out how to have a better error message for this...

On January 24, 2019 8:16:28 PM UTC, Steven Hatzakis <notifications@github.com> wrote:
>Seems like I am getting some ssl error after running with `ots` -vv
>stamp`:
>
>`Doing` 2-of-4 request, timeout is 5 seconds
>Submitting to remote calendar https://a.pool.opentimestamps.org
>Submitting to remote calendar https://b.pool.opentimestamps.org
>Submitting to remote calendar https://a.pool.eternitywall.com
>Submitting to remote calendar https://ots.btc.catallaxy.com
><urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
>failed: unable to get local issuer certificate (_ssl.c:1051)>
><urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
>failed: unable to get local issuer certificate (_ssl.c:1051)>
><urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
>failed: unable to get local issuer certificate (_ssl.c:1051)>
><urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
>failed: unable to get local issuer certificate (_ssl.c:1051)>
>Failed to create timestamp: need at least 2 attestations but received 0
>within timeout`
>
>Thanks for the help with this, would love to get it to work. 

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by hatgit** [comment]
Glad the error has been identified! I'm running Mac OS Mojave version 10.14.1. 
Are you familiar with any workaround to add the certs to the local python implementation? (Googling that now).

**Comment by hatgit** [comment]
P.S. do you have any suggestions on how to best add the root certificates to verify these connections securely?

**Comment by petertodd** [comment]
I don't have a Mac, so I've never had to do this. But see if this advice helps: https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore

**Comment by hatgit** [comment]
Seems to have been resolved after the suggestion on that Stackoverflow post to use: `cd /Applications/Python\ 3.7/` and then `./Install\ Certificates.command` which upgrades the "certifi" package. Then I was able to create a .ots file that was stamped, and now pending verification on the Bitcoin chain! Thanks for all the help with this, I guess it can now be considered resolved (assuming the verification is completed in the next few hours).

**Comment by petertodd** [comment]
Great!

If you want to make a pull-req to add those instructions to the README that'd be awesome, thanks!

**Comment by hatgit** [comment]
Done, let me know if it needs any revision, thanks!

**Comment by petertodd** [comment]
Yup, as I [mentioned](https://github.com/opentimestamps/python-opentimestamps/pull/39#issuecomment-471049627) if you want to add those instructions to the `opentimestamps-client` README that'd be great.

Looks like this issue can be closed.
