### ISSUE TITLE
Add Support For BLAKE3

### ISSUE THREAD

**Issue by InnovativeInventor** [opentimestamps/python-opentimestamps#42]
[BLAKE3](https://github.com/BLAKE3-team/BLAKE3) is very new, shiny, and fast! 

Python is planning to add it to hashlib: https://bugs.python.org/issue39298

I'm trying to quickly timestamp a few TB hard drives worth of files and the speed of BLAKE3 would be very nice to have.

**Comment by petertodd** [comment]
Closing as "won't fix", as Python never added it. Also, SHA256 accelerator opcodes are (finally!) becoming more commonly available in CPUs, and that's likely to increase even further over time: https://en.wikipedia.org/wiki/Intel_SHA_extensions
