### ISSUE TITLE
Scrypt Op

### ISSUE THREAD

**Issue by NCGThompson** [opentimestamps/python-opentimestamps#44]
Even if no current OTS implementations support Litecoin (LTC), Scrypt should at least be in the .ots vocabulary.

In order for a proof to be verified with just a trusted block header, the .ots files need to contain a Merkle brach of the blockchain used. Since LTC uses Scrypt as its hash function, the .ots needs to convey the Scrypt hash function if LTC is used.

Development on LTC support by a third party can't start until there is a consensus on how to serialize/deserialize Scrypt.

**Comment by petertodd** [comment]
On Fri, Mar 12, 2021 at 08:54:45PM -0800, Nic wrote:
> Even if no current OTS implementations support Litecoin (LTC), Scrypt should at least be in the .ots vocabulary.
> 
> In order for a proof to be verified with just a trusted block header, the .ots files need to contain a Merkle brach of the blockchain used. Since LTC uses Scrypt as its hash function, the .ots needs to convey the Scrypt hash function if LTC is used.
> 
> Development on LTC support by a third party can't start until there is a consensus on how to serialize/deserialize Scrypt.

You're mistaken. Litecoin only uses Scrypt for its proof-of-work function. The
merkle tree itself uses SHA256, just like Bitcoin.

-- 
https://petertodd.org ***@***.***

**Comment by NCGThompson** [comment]
> You're mistaken. Litecoin only uses Scrypt for its proof-of-work function. The
merkle tree itself uses SHA256, just like Bitcoin.

I stand corrected. Here is [some source code](https://github.com/litecoin-project/litecoin/blob/master/src/consensus/merkle.cpp) that uses SHA256D64.

Scrypt is pretty useless unless we are worried about a presage attack.
