### ISSUE TITLE
OpPad?

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/python-opentimestamps#6]
Is concatenation of message chunks - separating by junk padding - a valid/useful commitment operation? Specifically, imagine our commitment operation takes a message, and a list of padding chunks as the argument:

```
<delta idx 1> <padding chunk 1> ... <delta idx n> <padding chunk n>
```

and produces the result by taking the message, and inserting the padding chunks appropriately.

This should still be a commitment operation, as for a given set of padding and a given message, the result will always be the same; it's essentially a very fancy OpAppend.

**Comment by petertodd** [comment]
Note, if the # of padding chunks is allowed to be too many, this is pretty obviously broken as it gives too many degrees of freedom to change what you're committing to after the fact. E.g. imagine if you allowed 32 padding chunks, each committing to all bytes 00 .. ff

But if the number of degrees of freedom is constrained, this is still a valid commitment.

**Comment by federicobond** [comment]
My first impression is that it does not add more expressivity and makes clients harder to implement and more prone to bugs. What's the use case you were thinking of?

**Comment by petertodd** [comment]
@federicobond Well, it only makes sense for niche stuff where you're trying to get a timestamp proof out of something that wasn't meant to provide one; not general use.

Anway, probably fine to close for now and focus on more important stuff!
